### ISSUE TITLE
Decoding mp3 to flac wrongly

### ISSUE THREAD

**Issue by Kennnnnnji** [luanxuechao/qn-decode#1]
http://music.163.com/song?id=1463338826

It's a 320K HQ file (in fact a mp3), but is decoded to a flac file using qn-decode.

![image](https://user-images.githubusercontent.com/34367558/101156539-b9b15180-3663-11eb-8a97-2e77a41c402a.png)

From this pic, you can see the result file is a lame mp3 file, but the extension is wrongly named as ".flac".

**Comment by luanxuechao** [comment]
At present, the file is recognized by the extension, not the file header. @Kennnnnnji

**Comment by Kennnnnnji** [comment]
Yes. I mean the .ncm conversion result is "xxx.flac" instead of ".mp3".
But the audio should be ".mp3" in fact, it should be a lossy audio file.
Can you recognize if a .ncm file is a mp3 or flac file?

**Comment by luanxuechao** [comment]
Yes, you can see this code https://github.com/luanxuechao/qn-decode/blob/a3497bd65e726cf13e2cdf0752cc8c0abb1541bb/util/decodeNcm.go#L316
